// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBULaCoqJrQH1WlnIsTuw5Dt6gjMGjljU4',
    appId: '1:1008664164309:web:9fb9bf2a115ae8caf9af5c',
    messagingSenderId: '1008664164309',
    projectId: 'gamememory-9ab53',
    authDomain: 'gamememory-9ab53.firebaseapp.com',
    databaseURL: 'https://gamememory-9ab53-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gamememory-9ab53.firebasestorage.app',
    measurementId: 'G-4NZ9BS6RMX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN4FPsGvAXTbV7-OG5RFBbWNf_7ia3I-Y',
    appId: '1:1008664164309:android:7f98641898225e23f9af5c',
    messagingSenderId: '1008664164309',
    projectId: 'gamememory-9ab53',
    databaseURL: 'https://gamememory-9ab53-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gamememory-9ab53.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN4FPsGvAXTbV7-OG5RFBbWNf_7ia3I-Y',
    appId: '1:1008664164309:ios:7f98641898225e23f9af5c',
    messagingSenderId: '1008664164309',
    projectId: 'gamememory-9ab53',
    databaseURL: 'https://gamememory-9ab53-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gamememory-9ab53.firebasestorage.app',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBN4FPsGvAXTbV7-OG5RFBbWNf_7ia3I-Y',
    appId: '1:1008664164309:ios:7f98641898225e23f9af5c',
    messagingSenderId: '1008664164309',
    projectId: 'gamememory-9ab53',
    databaseURL: 'https://gamememory-9ab53-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gamememory-9ab53.firebasestorage.app',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBN4FPsGvAXTbV7-OG5RFBbWNf_7ia3I-Y',
    appId: '1:1008664164309:web:7f98641898225e23f9af5c',
    messagingSenderId: '1008664164309',
    projectId: 'gamememory-9ab53',
    authDomain: 'gamememory-9ab53.firebaseapp.com',
    databaseURL: 'https://gamememory-9ab53-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gamememory-9ab53.firebasestorage.app',
  );
}
